In [1]:
import numpy as np

#Generating Array

In [57]:
K=np.array(([2,5,7],[6,2,1],[0,6,3]))
K

array([[2, 5, 7],
       [6, 2, 1],
       [0, 6, 3]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Making array of random numbers

In [31]:
np.random.random(2)

array([0.71785627, 0.03098074])

In [32]:
np.random.randint(1,10,5)

array([7, 1, 1, 8, 1])

In [40]:
np.random.randn(1,3)

array([[-1.19307444, -0.41443481,  0.33004265]])

In [56]:
a=np.arange(1,3)
b=np.arange(10,14)
np.meshgrid(a,b)

[array([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]),
 array([[10, 10],
        [11, 11],
        [12, 12],
        [13, 13]])]

#Inspecting array

In [58]:
K.shape

(3, 3)

In [59]:
K.size

9

In [60]:
len(K)

3

In [62]:
K.ndim

2

In [63]:
K.dtype

dtype('int64')

In [65]:
K.astype(bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

#Operations with array

In [70]:
a=np.arange(1,5)
b=np.arange(5,9)
np.add(a,b)

array([ 6,  8, 10, 12])

In [71]:
np.subtract(b,a)

array([4, 4, 4, 4])

In [72]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [73]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [74]:
np.floor_divide(a,b)

array([0, 0, 0, 0])

In [75]:
np.mod(a,b)

array([1, 2, 3, 4])

In [79]:
np.power(a,3)

array([ 1,  8, 27, 64])

In [77]:
np.equal(a,b)

array([False, False, False, False])

In [80]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [81]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [82]:
np.square(a)

array([ 1,  4,  9, 16])

In [86]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [84]:
np.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105])

In [85]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [87]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [88]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [97]:
c=np.array([1.683789,-3.799006,5.99999])
np.round(c,3)

array([ 1.684, -3.799,  6.   ])

In [98]:
np.abs(c)

array([1.683789, 3.799006, 5.99999 ])

In [101]:
np.sign(a)

array([1, 1, 1, 1])

In [102]:
np.isnan(a)

array([False, False, False, False])

#Some Important np